### ISSUE TITLE
无法下载，是否接口已更新？

### ISSUE THREAD

**Issue by UVJkiNTQ** [kuloPo/TencentDocDownload#6]
Traceback (most recent call last):
  File "excel.py", line 11, in <module>
    title, tabs, opendoc_params = download.initial_fetch(url)
  File "C:\Users\luke\Desktop\TencentDocDownload-main\download.py", line 30, in initial_fetch
    opendoc_json = read_callback(opendoc_text)
  File "C:\Users\luke\Desktop\TencentDocDownload-main\download.py", line 76, in read_callback
    content = re.search(r"clientVarsCallback\(\"(.+)\"\)", text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by Pluto-123** [comment]
同问 解决了吗？

**Comment by cjjduck** [comment]
同问，解决了吗？

**Comment by YXH-YXH** [comment]
是因为跨域访问+没有cookies缓存的原因
在download文件增加
`
    header={
        "Referer":re.search(r"(.+)\?|(.+)",init_url).group(0),
        "cookie":"。。请使用自己的cookies。。",
    }
`
以及请求网络页面时
`
    opendoc_text = requests.get(opendoc_url, headers=header, params=opendoc_params).text
`
(增加headers=header)

---------------------------------------------------------
1.稍后我提交一下requests，展示一下更改内容
2.关于如何获取cookie，建议自行百度

**Comment by YXH-YXH** [comment]
> 是因为跨域访问+没有cookies缓存的原因 在download文件增加 `header={ "Referer":re.search(r"(.+)\?|(.+)",init_url).group(0), "cookie":"。。请使用自己的cookies。。", }` 以及请求网络页面时 `opendoc_text = requests.get(opendoc_url, headers=header, params=opendoc_params).text` (增加headers=header)
> 
> 1.稍后我提交一下requests，展示一下更改内容 2.关于如何获取cookie，建议自行百度

已解决的分支
https://github.com/YXH-YXH/TencentDocDownload
